# Generated by Django 5.1.3 on 2024-11-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_Conta', models.AutoField(primary_key=True, serialize=False)),
                ('Banco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('DEPOSITO_FIXO', 'Depósito Fixo'), ('DESCONTO_FIXO', 'Desconto Fixo'), ('PIX', 'PIX')], max_length=20)),
                ('parcelado', models.BooleanField(default=False)),
                ('parcelas', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('valor_parcelas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fixo', models.BooleanField(default=False)),
                ('desconto', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.conta')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.pessoa'),
        ),
    ]
