# Generated by Django 5.1.3 on 2024-11-21 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cartao', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('DEPOSITO_FIXO', 'Depósito Fixo'), ('DESCONTO_FIXO', 'Desconto Fixo'), ('PIX', 'PIX')], max_length=20)),
                ('origem_ou_motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('parcelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saldo_disponivel', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('banco_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('divida_paga', models.BooleanField(default=False)),
                ('data_pago', models.DateField(blank=True, null=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.cartao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='cartao',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.pessoa'),
        ),
    ]
