# Generated by Django 5.1.3 on 2024-11-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoconta',
            name='Pago',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
