# Generated by Django 5.1.3 on 2024-11-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_movimentacaoconta_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoconta',
            name='fixo',
        ),
    ]
