# Generated by Django 5.1.3 on 2024-11-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_remove_movimentacaoconta_fixo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoconta',
            name='Pago',
        ),
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='tipo',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('PIX', 'PIX'), ('PAGAMENTO FATURA', 'Pagamento Fatura'), ('Investimento', 'Investimento'), ('Fundo De Emergência', 'Fundo De Emergência')], max_length=20),
        ),
    ]
